package Fitur;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import laporan.db_koneksi;
import laporan.pilihlaporanawaladmin;

public class supplier extends javax.swing.JFrame {
    public supplier(String id_user) {
        initComponents();
        this.setResizable(false);
        load_table();
        kosong();
        autonumber();
        setName(id_user);
        tampil_tanggal();
        tampil_waktu();
        }
    
    public void setName(String user) {
        txt_username.setText(user);
    }
    
    private void tampil_tanggal(){
        java.util.Date tglsekaran = new java.util.Date();
        SimpleDateFormat oi = new SimpleDateFormat("EEEE dd MMMM YYYY", Locale.getDefault());
        String tanggal = oi.format(tglsekaran);
        txt_tanggal.setText(tanggal);
    }
    
    private void tampil_waktu(){
        ActionListener taskPerformer = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "", nol_menit = "", nol_detik = "";
            
                java.util.Date dateTime = new java.util.Date();
                int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();
            
                if(nilai_jam <= 9) nol_jam = "0";
                if(nilai_menit <= 9) nol_jam = "0";
                if(nilai_detik <= 9) nol_jam = "0";
            
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
            
                txt_waktu.setText(jam + ":" + menit + ":" + detik + "");
            }      
        };
        new Timer(1000, taskPerformer).start(); 
    }   
    
       private void load_table() {
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");
            model.addColumn("ID Supplier");
            model.addColumn("Nama Supplier");
            model.addColumn("Telepon");
            model.addColumn("Alamat");
   
       try {
            int no = 1;
            String sql = "SELECT * FROM supplier";
            java.sql.Connection conn = (Connection)db_koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, 
                    res.getString(1), 
                    res.getString(2), 
                    res.getString(3), 
                    res.getString(4)                    
                });   
            }
            jTable1.setModel(model);
            } catch (SQLException e) {            
        }
    }
    
    private void kosong() {
        txtidSupplier.setText(null);
        txtnamasupp.setText(null);
        txttelepon.setText(null);
        txtalamat.setText(null);
        autonumber();
    }
    
    private void autonumber() {
       try {
           String sql = "SELECT MAX(id_supp) AS ID FROM supplier";
           java.sql.Connection conn = (Connection)db_koneksi.configDB();
           java.sql.Statement pst = conn.createStatement();
           java.sql.ResultSet rs = pst.executeQuery(sql);
           while(rs.next()) {
               Object[] obj = new Object[1];
               obj[0] = rs.getString("ID");
               if(obj[0] == null) {
                   obj[0] = "SP00000000";
               }
               String str_id = (String) obj[0];
               String kd = str_id.substring(2, 10);
               int int_code = Integer.parseInt(kd);
               int_code++;
               String a = String.format("%08d", int_code);
               String b = "SP" + a;
               txtidSupplier.setText(b);
               txtidSupplier.setEditable(false);
               }
           } catch (NumberFormatException | SQLException e) {      
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtidSupplier = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnamasupp = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        linkBarang = new javax.swing.JButton();
        linkBarang1 = new javax.swing.JButton();
        linkBarang2 = new javax.swing.JButton();
        linkBarang3 = new javax.swing.JButton();
        linkBarang4 = new javax.swing.JButton();
        linkBarang5 = new javax.swing.JButton();
        linkBarang6 = new javax.swing.JButton();
        linkBarang7 = new javax.swing.JButton();
        txt_waktu = new javax.swing.JLabel();
        txt_tanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 760));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setBackground(new java.awt.Color(255, 204, 153));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setRowHeight(35);
        jTable1.setSelectionBackground(new java.awt.Color(245, 150, 92));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 770, 340));

        txtidSupplier.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtidSupplier.setAlignmentX(1.0F);
        txtidSupplier.setAlignmentY(1.0F);
        txtidSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtidSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 215, 145, 30));

        txtalamat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 215, 145, 30));
        txtalamat.getAccessibleContext().setAccessibleName("");

        txtnamasupp.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        getContentPane().add(txtnamasupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 145, 30));

        txttelepon.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        getContentPane().add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 145, 30));

        btnSimpan.setBackground(new java.awt.Color(245, 150, 92));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon/Karyawan.png"))); // NOI18N
        btnSimpan.setText("TAMBAH");
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 40));

        btnEdit.setBackground(new java.awt.Color(245, 150, 92));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon/edit.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 90, 40));

        btnClear.setBackground(new java.awt.Color(245, 150, 92));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon/brush.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 100, 40));

        btnHapus.setBackground(new java.awt.Color(245, 150, 92));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ikon/bin.png"))); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(939, 360, -1, 40));

        linkBarang.setOpaque(false);
        linkBarang.setContentAreaFilled(false);
        linkBarang.setBorderPainted(false);
        linkBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarangActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 50));

        linkBarang1.setOpaque(false);
        linkBarang1.setContentAreaFilled(false);
        linkBarang1.setBorderPainted(false);
        linkBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang1ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 200, 50));

        linkBarang2.setOpaque(false);
        linkBarang2.setContentAreaFilled(false);
        linkBarang2.setBorderPainted(false);
        linkBarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang2ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 50));

        linkBarang3.setOpaque(false);
        linkBarang3.setContentAreaFilled(false);
        linkBarang3.setBorderPainted(false);
        linkBarang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang3ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 200, 50));

        linkBarang4.setOpaque(false);
        linkBarang4.setContentAreaFilled(false);
        linkBarang4.setBorderPainted(false);
        linkBarang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang4ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 200, 50));

        linkBarang5.setOpaque(false);
        linkBarang5.setContentAreaFilled(false);
        linkBarang5.setBorderPainted(false);
        linkBarang5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang5ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 140, 40));

        linkBarang6.setOpaque(false);
        linkBarang6.setContentAreaFilled(false);
        linkBarang6.setBorderPainted(false);
        linkBarang6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang6ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 200, 50));

        linkBarang7.setOpaque(false);
        linkBarang7.setContentAreaFilled(false);
        linkBarang7.setBorderPainted(false);
        linkBarang7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarang7ActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 200, 50));

        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_username.setText("Username");
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 120, 130, 40));

        txt_waktu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txt_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 80, 40));

        txt_tanggal.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txt_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Supplier Admin REVISI.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 770));

        jLabel5.setText("jLabel2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, -1, -1));

        jLabel6.setText("jLabel2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void txtidSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidSupplierActionPerformed
        txtidSupplier.setVisible(true);       
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidSupplierActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            String sql = "INSERT INTO supplier VALUES ('" + txtidSupplier.getText() +  "','" + txtnamasupp.getText()
                    + "','" + txttelepon.getText() + "','" + txtalamat.getText() + "')";
            java.sql.Connection conn = (Connection) db_koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Supplier Berhasil Di Tambahkan");          
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        load_table();
//        autonumber();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
            try {
            String sql = "UPDATE supplier SET nama_supp = '"+txtnamasupp.getText() 
                    +"',alamat = '"+txtalamat.getText()+"',telp_supp = '"+txttelepon.getText()+
                    "'WHERE id_supp ='"+txtidSupplier.getText()+"'";
            java.sql.Connection conn = (Connection)db_koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Perbarui");
            
            } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal!!"+e.getMessage());
        }
        load_table();
        kosong();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int pop = JOptionPane.showConfirmDialog(this, "Beneran di hapus?", "Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pop == JOptionPane.YES_OPTION) {                
            
        try {
            String sql = "DELETE FROM supplier WHERE id_supp = '"+txtidSupplier.getText()+"'";
            java.sql.Connection conn = (Connection)db_koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int row = jTable1.getSelectedRow();
            model.removeRow(row);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        load_table();
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String kode_barang = jTable1.getValueAt(baris, 1).toString();
        txtidSupplier.setText(kode_barang);
        
        if (jTable1.getValueAt(baris, 2)==null) {
            txtnamasupp.setText("");
        } else {
            txtnamasupp.setText(jTable1.getValueAt(baris, 2).toString());
        }
        if (jTable1.getValueAt(baris, 3)==null) {
            txttelepon.setText("");
        } else {
            txttelepon.setText(jTable1.getValueAt(baris, 3).toString());
        }
        if (jTable1.getValueAt(baris, 4)==null) {
            txtalamat.setText("");
        } else {
            txtalamat.setText(jTable1.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void linkBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarangActionPerformed
        this.setVisible(false);
        new Home(txt_username.getText()).setVisible(true);
    }//GEN-LAST:event_linkBarangActionPerformed

    private void linkBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang1ActionPerformed
        this.setVisible(false);
        new cashier(txt_username.getText()).setVisible(true);
    }//GEN-LAST:event_linkBarang1ActionPerformed

    private void linkBarang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang2ActionPerformed
        this.setVisible(false);
        new pilihlaporanawaladmin(txt_username.getText()).setVisible(true);
    }//GEN-LAST:event_linkBarang2ActionPerformed

    private void linkBarang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang3ActionPerformed
        this.setVisible(false);
        new formBarang(txt_username.getText()).setVisible(true);
    }//GEN-LAST:event_linkBarang3ActionPerformed

    private void linkBarang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang4ActionPerformed
        this.setVisible(false);
        new BarangMasuk(txt_username.getText()).setVisible(true);                                                                                                                                                
    }//GEN-LAST:event_linkBarang4ActionPerformed

    private void linkBarang5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang5ActionPerformed
        int respons = JOptionPane.showConfirmDialog(this, "Yakin Logout ?", "Log Out", JOptionPane.
        YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respons==JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new formLogin1().setVisible(true); 
            JOptionPane.showMessageDialog(null, "Anda berhasil Log Out");
        } else {
        }  
    }//GEN-LAST:event_linkBarang5ActionPerformed

    private void linkBarang6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang6ActionPerformed
        setVisible(false);
        new Profil(txt_username.getText()).setVisible(true);
    }//GEN-LAST:event_linkBarang6ActionPerformed

    private void linkBarang7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarang7ActionPerformed
        this.setVisible(false);
        new Karyawan(txt_username.getText()).setVisible(true);
    }//GEN-LAST:event_linkBarang7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new supplier(txt_username.getText()).setVisible(true);
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton linkBarang;
    private javax.swing.JButton linkBarang1;
    private javax.swing.JButton linkBarang2;
    private javax.swing.JButton linkBarang3;
    private javax.swing.JButton linkBarang4;
    private javax.swing.JButton linkBarang5;
    private javax.swing.JButton linkBarang6;
    private javax.swing.JButton linkBarang7;
    private javax.swing.JLabel txt_tanggal;
    public static final javax.swing.JLabel txt_username = new javax.swing.JLabel();
    private javax.swing.JLabel txt_waktu;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtidSupplier;
    private javax.swing.JTextField txtnamasupp;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables

}
    
